name: JAVA CI with Maven in Linux
on:
 push:
 pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      workdir: ./com.mycompany.orderAssignmentSystem
    strategy:
      matrix:
        include:
        - java: 8
          additional-maven-args: "-Pmutation-testing-with-coverage"
        - java: 11
    name: Build with Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml','**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        xvfb-run mvn verify ${{matrix.additional-maven-args}}  
      working-directory: ${{ env.workdir }}
    - name: Generate JUnit Report
      run: >
        mvn surefire-report:report-only site:site -DgenerateReport=false
      working-directory: ${{env.workdir}}
      if: ${{ always () }}
    - name: ArchiveJUnitReport
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
       name: surefire-report-jdk-${{ matrix.java }}
       path: '**/target/site'
    - name: ArchiveJaCoCoReport
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
          name: jacoco-report-jdk-${{ matrix.java }}
          path: '**/target/site/jacoco'
    - name: ArchivePitReport
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
          name: pit-report-jdk-${{ matrix.java }}
          path: '**/target/pit-reports'
    - name: ArchiveLogs
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
         name: log-files
         path: './*.log'        