# Operating System: Ubuntu
# Java Versions: Java 8 
# Tests: All tests (Integration, End-to-End and End-to-End with cucumber)
# Reports: FailSafeReport
name: JAVA IT, E2E tests and E2E with cucumber with Maven in Linux

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      workdir: ./com.mycompany.orderassignmentsystem
    strategy:
      matrix:
        include:
          - java: 8
            additional-maven-args: "-Pintegration-test-profile -Dpostgres.user=$USER -Dpostgres.password=$PASSWORD  -Dpostgres.dbName=$DATABASE -Dpostgres.server=maven"
    name: Build with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml','**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Check directory
        run: ls
      - name: Build with Maven
        run: xvfb-run mvn verify ${{ matrix.additional-maven-args }}
        working-directory: ${{ env.workdir }}
        env:
          DATABASE: ${{secrets.DATABASE}} 
          USER: ${{secrets.USER}} 
          PASSWORD: ${{secrets.PASSWORD}} 
      - name: ArchiveFailSafeReport
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: failsafe-report-jdk-${{ matrix.java }}
          path: '**/target/failsafe-reports'