name: JAVA IT with Maven in Linux

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      workdir: ./com.mycompany.orderAssignmentSystem
    strategy:
      matrix:
        include:
          - java: 8
            additional-maven-args: "-Pintegration-test-profile"
    name: Build with Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml','**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Generate persistence.xml
        run: |
          mkdir -p src/main/resources/META-INF/
          echo '<?xml version="1.0" encoding="UTF-8"?>' > src/main/resources/META-INF/persistence.xml
          echo '<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd" version="2.0">' >> src/main/resources/META-INF/persistence.xml
          echo '  <persistence-unit name="OriginalPersistenceUnit" transaction-type="RESOURCE_LOCAL">' >> src/main/resources/META-INF/persistence.xml
          echo '    <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>' >> src/main/resources/META-INF/persistence.xml
          echo '    <class>com.mycompany.orderAssignmentSystem.model.CustomerOrder</class>' >> src/main/resources/META-INF/persistence.xml
          echo '    <class>com.mycompany.orderAssignmentSystem.model.Worker</class>' >> src/main/resources/META-INF/persistence.xml
          echo '    <properties>' >> src/main/resources/META-INF/persistence.xml
          echo '      <property name="javax.persistence.jdbc.url" value="${{secrets.JDBC_URL}}" />' >> src/main/resources/META-INF/persistence.xml
          echo '      <property name="javax.persistence.jdbc.user" value="${{secrets.USER}}"/>' >> src/main/resources/META-INF/persistence.xml
          echo '      <property name="javax.persistence.jdbc.password" value="${{secrets.PASSWORD}}" />' >> src/main/resources/META-INF/persistence.xml
          echo '      <property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQLDialect" />' >> src/main/resources/META-INF/persistence.xml
          echo '      <property name="hibernate.hbm2ddl.auto" value="create-drop" />' >> src/main/resources/META-INF/persistence.xml
          echo '    </properties>' >> src/main/resources/META-INF/persistence.xml
          echo '  </persistence-unit>' >> src/main/resources/META-INF/persistence.xml
          echo '</persistence>' >> src/main/resources/META-INF/persistence.xml
